### PR TITLE
Fix windows build

### LINKED ISSUE #64: Warning free build
I suggest going for `-Werror` on the CI and removing the suppressed warnings. This avoids situations like #56 occurring in projects using this.

Challenges:

- Boost may produce warnings
  - add the "regular" boost includes to `-isystem`
  - Not sure how to do this in b2 though
- Internal warnings
  - Unused variable warning fixed in #61
  - Unused function warnings can be suppressed per-file or the functions can be (dummy-)used

### PR DESCRIPTION
**Pull request by Flamefire**
Our builds using Turtle were failing due to `#if BOOST_MSVC` being used instead of `#ifdef BOOST_MSVC` causing a "-Wundef" warning and an unused parameter warning

This PR enables warnings in the CMake build, adds CMake builds to appveyor and fixes the issues found.

Closes #64

### CODE REVIEW

**Comment by Flamefire** [comment]
@mat007 Mostly passing now. But got one more warning:

```
/home/travis/build/mat007/turtle/include/turtle/detail/../constraints.hpp:31:5: error: empty macro arguments are a C99 feature [-Werror,-Wc99-extensions]

/home/travis/build/mat007/turtle/include/turtle/constraint.hpp:204:43: note: expanded from macro 'MOCK_NARY_CONSTRAINT'

                    << BOOST_PP_REPEAT(n, MOCK_CONSTRAINT_FORMAT, _) \
```

Maybe just remove all C++98 tests and declare this C++11 compatible? I'll disable those for now.

**Comment by mat007** [comment]
> Maybe just remove all C++98 tests and declare this C++11 compatible? I'll disable those for now.

Yeah it’s been almost 10 years now, I think that’d be fine 😁

**Comment by Flamefire** [comment]
Ok, done. BTW: https://github.com/mat007/turtle/pull/83/commits/8530f691a1f7da21eeb357a743f97d29c2760c17 cuts appveyor times in half :) Together with the other changes appveyor is about 6 times faster in total

**Comment by Flamefire** [comment]
Builds all green. You may want to re-setup travis as it doesn't report. Build here: https://travis-ci.org/github/mat007/turtle/builds/676629507

**Comment by mat007** [comment]
> You may want to re-setup travis as it doesn't report.

I took a look and all I could find was flipping the «integration enabled» switch off and on again…

image

**Comment by mat007** [comment]
Ah and it did seems it wake Travis up as it’s now build master…

image

**Pull request merged**
